@echo off
echo Stopping existing Node.js processes...
taskkill /F /IM node.exe >nul 2>&1
echo Waiting 3 seconds...
timeout /t 3 /nobreak >nul
echo Starting API server...
cd /d "C:\Users\usair\Downloads\react-car\trailcommand-api"
start "TrailCommand API" npm start
echo Server restarting...